export {default as LoginCTR} from './login/Login'
export {default as SignupCTR} from './signup/Signup'
export {default as ApplicationCTR} from './application/applicationCTR'
export {default as HomeCTR} from './home/HomeCTR'
export {default as AdminHomeCTR} from './adminHome/adminHomeCTR'